config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

  # Defines the root path route ("/")
  # root "articles#index"
  root 'users#index'

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy]
  end

  resources :posts do
    resources :comments, only: [:create, :destroy]
    resources :likes, only: [:create]
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# User model class
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :validatable
  has_many :posts, foreign_key: 'user_id', class_name: 'Post'
  has_many :comments, foreign_key: 'user_id', class_name: 'Comment'
  has_many :likes, foreign_key: 'user_id', class_name: 'Like'

  ROLES = %I[admin defaut].freeze
  after_save :recent_posts

  # validations
  validates :name, presence: true
  validates :email, uniqueness: true
  validates :posts_counter, numericality: { only_integer: true, greater_than: -1 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def is?(requested_role)
    ROLES == requested_role.to_s
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    users = User.all
    render json: users
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def index; end

  def show; end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
  protect_from_forgery with: :null_session

  respond_to :json

  private

  def respond_with(resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed
  end

  def register_success
    render json: { message: 'Signed up sucessfully.' }
  end

  def register_failed
    render json: { message: 'Something went wrong.' }
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  protect_from_forgery with: :null_session

  respond_to :json

  private

  def respond_with(resource, _opts = {})
    render json: resource
  end

  def respond_to_on_destroy
    log_out_success && return if current_user

    log_out_failure
  end

  def log_out_success
    render json: { message: 'You are logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Hmm nothing happened.' }, status: :unauthorized
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order(:name)
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

app/views/users/index.html.erb
<h1>Here is a list of users</h1>

<% @users.each do |user| %>
    <%= render partial: 'shared/user', locals: { user: user } %>
 <% end %>

app/views/users/show.html.erb
<h1>Details of a user</h1>
<section class="py-4">
  <div class="card mb-3" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4">
        <img src="<%= @user.photo%>" class="img-fluid rounded-start" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title display-6 fw-bold"><%= @user.name %></h5>
          <p class="card-text"><%= @user.bio %></p>
          <p class="card-text"><small class="text-muted">Number of posts: <%= @user.posts_counter || 0 %> <%= %></small></p>
        </div>
      </div>
    </div>
  </div>
  <div class='posts mt-5'>
    <% @user.recent_posts.each_with_index do |post,index| %>
      <div class="post p-2 mb-4">
        <h3 class="display-6"><%= post.title %></h3>
        <p><%= post.text%></p>
        <small><%= link_to "Details", user_post_path(@user.id,post.id), class: "link-to"%></small>
        <div class="d-flex justify-content-end">
          <span class="">Comments: <span class="value"><%= post.comments_counter || 0 %></span> </span>
          <span class="float-right">, Likes:<span class="value"> <%= post.likes_counter || 0 %></span></span>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to "See all posts", user_posts_path(@user.id) , class: "link-to d-flex justify-content-center" %>
</section>